---
# tasks file for deploy_app

- name: Create Root Dir
  ansible.builtin.file:
    path: "{{ image_root_dir }}"
    state: directory
    mode: "0644"
    owner: root
    group: root

- name: Upload Image
  ansible.builtin.copy:
    src: "{{ master_image_root_dir }}/server-image.tar"
    dest: "{{ image_root_dir }}/server-image.tar"
    mode: "0644"
    owner: root
    group: root

- name: Load Image
  community.docker.docker_image_load:
    path: "{{ image_root_dir }}/server-image.tar"

- name: Down Previous Container
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: absent
    force_kill: true
    keep_volumes: false
    auto_remove: true
  register: container_removal_result

- name: Container Removal Result
  ansible.builtin.debug:
    var: container_removal_result

- name: Run New Image
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ app_name }}:latest"
    state: started
    ports:
      - 83:80
    restart_policy: always
    # cpus: 0.5
    env:
      PORT: "80"

- name: Clean Up
  ansible.builtin.file:
    path: "{{ image_root_dir }}/server-image.tar"
    state: absent
