name: Dockerize and Deploy

on:
  push:
    branches: ["main"]

jobs:
  Dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image
        run: |
          ls -ah
          docker build -t my-node-service ./service 
          rm -r ./out/server-image.tar || true
          mkdir -p ./out
          docker save --output=./out/server-image.tar my-node-service:latest
          ls -lh ./out/server-image.tar
          tar tf ./out/server-image.tar
